"""initial schema

Revision ID: d335dfe368c0
Revises: 
Create Date: 2026-09-07 06:47:22.903419
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd335dfe368c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('school_colleges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('department_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('school_college_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_college_id'], ['school_colleges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('evaluator_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expertise', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tracking_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('lead_proponent_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'FOR_DEAN_ENDORSEMENT', 'ENDORSED_TO_URO', 'INITIAL_EVALUATION', 'INITIAL_EVALUATION_REVISION_REQUIRED', 'PROPOSAL_TURNITIN', 'PROPOSAL_TURNITIN_REVISION_REQUIRED', 'PROPOSAL_TURNITIN_PASSED', 'EXTERNAL_EVALUATION', 'EXTERNAL_EVALUATION_REVISION_REQUIRED', 'SELECTIVE_EXTERNAL_REEVALUATION', 'EXTERNAL_EVALUATION_PASSED', 'FOR_IRB_REVIEW', 'IRB_REVISION_REQUIRED', 'PROPOSAL_APPROVED', 'RESEARCH_IN_PROGRESS', 'FINAL_PAPER_DUE', 'FINAL_PAPER_SUBMITTED', 'FINAL_PAPER_TURNITIN', 'FINAL_PAPER_TURNITIN_REVISION_REQUIRED', 'FINAL_PAPER_TURNITIN_PASSED', 'FINAL_BLIND_EVALUATION', 'FINAL_EVALUATION_REVISION_REQUIRED', 'SELECTIVE_FINAL_REEVALUATION', 'FINAL_BLIND_EVALUATION_PASSED', 'COMPLETED', 'READY_FOR_PRESENTATION', 'READY_FOR_PUBLICATION', 'ARCHIVED', name='researchstatus'), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=True),
    sa.Column('nature_of_research', sa.String(length=100), nullable=True),
    sa.Column('target_journal', sa.String(length=200), nullable=True),
    sa.Column('research_agenda', sa.Text(), nullable=True),
    sa.Column('is_continuation', sa.Boolean(), nullable=True),
    sa.Column('continuation_ref', sa.String(length=200), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('institutional_email', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_proponent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_tracking_number'), 'research', ['tracking_number'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('research_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('affiliation', sa.String(length=200), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contribution_pct', sa.Integer(), nullable=True),
    sa.Column('is_lead', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_declarations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_id', sa.UUID(), nullable=False),
    sa.Column('declaration_type', sa.String(length=100), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('consented_by', sa.UUID(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consented_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_id', sa.UUID(), nullable=False),
    sa.Column('activity', sa.String(length=300), nullable=False),
    sa.Column('target_start', sa.Date(), nullable=True),
    sa.Column('target_end', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'DELAYED', 'CANCELLED', name='milestonestatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_readiness',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_id', sa.UUID(), nullable=False),
    sa.Column('ready_for_presentation', sa.Boolean(), nullable=True),
    sa.Column('ready_for_publication', sa.Boolean(), nullable=True),
    sa.Column('marked_by', sa.UUID(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_id')
    )
    op.create_table('user_affiliations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department_unit_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_unit_id'], ['department_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workflow_stage', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['research_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_id', sa.UUID(), nullable=False),
    sa.Column('evaluator_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_type', sa.Enum('PROPOSAL', 'FINAL', name='evaluationtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_INVITATION', 'ACCEPTED', 'DECLINED', 'IN_REVIEW', 'SUBMITTED', 'REEVALUATION_REQUIRED', 'SUPERSEDED', 'CANCELLED', name='assignmentstatus'), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('document_version_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['research_document_versions.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['evaluator_profiles.id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('irb_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('REVISION_REQUIRED', 'NOT_APPROVED', 'APPROVED', name='irbdecision'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['research_document_versions.id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_id', sa.UUID(), nullable=False),
    sa.Column('prior_status', sa.Enum('DRAFT', 'SUBMITTED', 'FOR_DEAN_ENDORSEMENT', 'ENDORSED_TO_URO', 'INITIAL_EVALUATION', 'INITIAL_EVALUATION_REVISION_REQUIRED', 'PROPOSAL_TURNITIN', 'PROPOSAL_TURNITIN_REVISION_REQUIRED', 'PROPOSAL_TURNITIN_PASSED', 'EXTERNAL_EVALUATION', 'EXTERNAL_EVALUATION_REVISION_REQUIRED', 'SELECTIVE_EXTERNAL_REEVALUATION', 'EXTERNAL_EVALUATION_PASSED', 'FOR_IRB_REVIEW', 'IRB_REVISION_REQUIRED', 'PROPOSAL_APPROVED', 'RESEARCH_IN_PROGRESS', 'FINAL_PAPER_DUE', 'FINAL_PAPER_SUBMITTED', 'FINAL_PAPER_TURNITIN', 'FINAL_PAPER_TURNITIN_REVISION_REQUIRED', 'FINAL_PAPER_TURNITIN_PASSED', 'FINAL_BLIND_EVALUATION', 'FINAL_EVALUATION_REVISION_REQUIRED', 'SELECTIVE_FINAL_REEVALUATION', 'FINAL_BLIND_EVALUATION_PASSED', 'COMPLETED', 'READY_FOR_PRESENTATION', 'READY_FOR_PUBLICATION', 'ARCHIVED', name='researchstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('DRAFT', 'SUBMITTED', 'FOR_DEAN_ENDORSEMENT', 'ENDORSED_TO_URO', 'INITIAL_EVALUATION', 'INITIAL_EVALUATION_REVISION_REQUIRED', 'PROPOSAL_TURNITIN', 'PROPOSAL_TURNITIN_REVISION_REQUIRED', 'PROPOSAL_TURNITIN_PASSED', 'EXTERNAL_EVALUATION', 'EXTERNAL_EVALUATION_REVISION_REQUIRED', 'SELECTIVE_EXTERNAL_REEVALUATION', 'EXTERNAL_EVALUATION_PASSED', 'FOR_IRB_REVIEW', 'IRB_REVISION_REQUIRED', 'PROPOSAL_APPROVED', 'RESEARCH_IN_PROGRESS', 'FINAL_PAPER_DUE', 'FINAL_PAPER_SUBMITTED', 'FINAL_PAPER_TURNITIN', 'FINAL_PAPER_TURNITIN_REVISION_REQUIRED', 'FINAL_PAPER_TURNITIN_PASSED', 'FINAL_BLIND_EVALUATION', 'FINAL_EVALUATION_REVISION_REQUIRED', 'SELECTIVE_FINAL_REEVALUATION', 'FINAL_BLIND_EVALUATION_PASSED', 'COMPLETED', 'READY_FOR_PRESENTATION', 'READY_FOR_PUBLICATION', 'ARCHIVED', name='researchstatus'), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_version_id'], ['research_document_versions.id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('similarity_check_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('PROPOSAL', 'FINAL_PAPER', name='turnitinstage'), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('threshold_at_decision', sa.Float(), nullable=True),
    sa.Column('result', sa.Enum('ACCEPTABLE', 'REVISION_REQUIRED', name='turnitinresult'), nullable=False),
    sa.Column('report_file', sa.String(length=500), nullable=True),
    sa.Column('annotations', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['research_document_versions.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('pass_fail', sa.String(length=10), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['evaluation_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['research_document_versions.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_submissions')
    op.drop_table('similarity_check_attempts')
    op.drop_table('research_status_history')
    op.drop_table('irb_reviews')
    op.drop_table('evaluation_assignments')
    op.drop_table('research_document_versions')
    op.drop_table('user_affiliations')
    op.drop_table('research_readiness')
    op.drop_table('research_milestones')
    op.drop_table('research_documents')
    op.drop_table('research_declarations')
    op.drop_table('research_authors')
    op.drop_table('notifications')
    op.drop_table('audit_events')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_research_tracking_number'), table_name='research')
    op.drop_table('research')
    op.drop_table('evaluator_profiles')
    op.drop_table('department_units')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('school_colleges')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
